LXPAPI/urls.py
from django.urls import include, path, re_path

from lxpapiapp.lxpappApiViews import *
from django.contrib.auth import views as auth_views
urlpatterns = [
    path("login/", LoginPage.as_view(), name="login"),
    path("api/v1/auth/", include("dj_rest_auth.urls")),
    re_path(r"^api/v1/auth/accounts/", include("allauth.urls")),
    path("api/v1/auth/registration/", include("dj_rest_auth.registration.urls")),
    path("api/v1/auth/google/", GoogleLogin.as_view(), name="google_login"),
    path(
        "api/v1/auth/google/callback/",
        GoogleLoginCallback.as_view(),
        name="google_login_callback", 
    ),
    path('complete/google/', google_complete, name='google_complete'),
    path('api/cto/', include('cto.urls')),
    path('api/cfo/', include('cfo.urls')),
    path('api/staff/', include('staff.urls')), 
    path('api/signup/', SignupAPIView.as_view(), name='api-signup'),
    path('api/loginuser/', LoginAPI.as_view(), name='api-login-user'),
    path('logout/', custom_logout, name='logout'),
    path('api/change-password/', ChangePasswordAPIView.as_view(), name='api-change-password'),
    path('api/admin/view-users/', AdminViewUserList.as_view(), name='api-admin-view-user-list'),
    path('api/admin/user-log-details/<int:user_id>/', AdminViewUserLogDetailsAPIView.as_view(), name='api-user-log-details'),
    path('api/admin/user-activity-details/<int:user_id>/', AdminViewUserActivityDetailsAPIView.as_view(), name='api-user-activity-details'),
    path('api/admin/toggle-user-status/<int:user_id>/', AdminToggleUserStatusAPIView.as_view(), name='api-toggle-user-status'),
    path('api/delete-user/<int:user_id>/', DeleteUserAPIView.as_view(), name='api-delete-user'),
    path('api/user-profile/', UserProfileView.as_view(), name='api-user-profile'),
    path('api/user-info/', UserInfoView.as_view(), name='user-info'),

]

cfo/urls.py
from django.urls import path
from cfo.cfoApiViews import *
urlpatterns = [
    path('batch/', BatchAPIView.as_view(), name='api-batch'),
    path('batch/<int:pk>/', BatchAPIView.as_view(), name='api-batch-detail'),
    
    path('schedulers/', SchedulerAPIView.as_view(), name='api-schedulers'),
    path('schedulers/<int:pk>/', SchedulerAPIView.as_view(), name='api-scheduler-detail'),
    path('schedulers/calendar/', SchedulerCalendarAPIView.as_view(), name='api-scheduler-calendar'),
    path('schedulers/meetings/', get_meetings, name='api-get-meetings'),
]

iLMS/urls.py
from django.urls import path,include
from django.contrib import admin
from ilmsapp import views
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path("", views.home, name='home'),
    path('cto/',include('cto.urls')),
    path('cfo/',include('cfo.urls')),
    path('learner/',include('learner.urls')),
    path('trainer/',include('trainer.urls')),
    #path('logout', LogoutView.as_view(template_name='ilmsapp/logout.html'),name='logout'),
    path('aboutus', views.aboutus_view),
    path('contactus', views.contactus_view),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('syncyoutube', views.syncyoutube_view,name='syncyoutube'),
    path('syncyoutube-start', views.syncyoutube_start_view,name='syncyoutube-start'),

    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(template_name='ilmsapp/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),

    path('admin-view-user', views.admin_view_user_view,name='admin-view-user'),
    path('active-user/<userid>/<int:pk>', views.active_user_view,name='active-user'),
    path('inactive-user/<int:pk>', views.inactive_user_view,name='inactive-user'),
    path('admin-update-course/<int:pk>', views.admin_update_course_view,name='admin-update-course'),
    path('admin-mark-usertype/<int:pk>', views.admin_mark_usertype_view,name='admin-mark-usertype'),
    
 
]

staff/urls.py
from django.urls import path
from staff.staffApiViews import *
urlpatterns = [
    path('material/', MaterialAPIView.as_view(), name='api-material'),
    path('material-upload-csv/', MaterialUploadDetailsCSVView.as_view(), name='api-material-upload-csv'),
    path('session-material/', SessionMaterialAPIView.as_view(), name='api-session-material'),
    path('mcq-questions/', McqQuestionAPIView.as_view(), name='api-mcq-question'),
    path('mcq-results/', McqResultAPIView.as_view(), name='api-mcq-result'),
    path('mcq-result-details/', McqResultDetailsAPIView.as_view(), name='api-mcq-result-details'),
    path('exams/', ExamAPIView.as_view(), name='api-exam'),
    path('exam-questions/', ExamQuestionDetailsAPIView.as_view(), name='api-exam-question'),
    path('exam-random-mcqquestions/', RandomMcqQuestionsView.as_view(), name='api-exam-random-mcqquestions'),
    path('exam-random-short-questions/', RandomShortQuestionsView.as_view(), name='api-exam-random-short-questions'),
    path('short-results/', ShortResultAPIView.as_view(), name='api-short-results'),
    path('short-result-details/', ShortResultDetailsAPIView.as_view(), name='api-short-result-details'),
    path('short-questions/', ShortQuestionAPIView.as_view(), name='api-short-questions'),
    path('pending-short-exam-results/', PendingShortExamResultAPIView.as_view(), name='api-pending-short-exam-results'),
    path('update-short-question-result/<int:pk>/', UpdateShortQuestionResultAPIView.as_view(), name='api-update-short-question-result'),
    path('save-short-question-result/<int:pk>/', SaveShortQuestionResultAPIView.as_view(), name='api-save-short-question-result'),
    ############Those API is confusing due to many tables are removed so till dont use it #######################
    path('learner-chapter/', LearnerChapterView.as_view(), name='api-learner-chapter'),
    path('learner-chapter-course/<int:user_id>/', LearnerChapterCourseView.as_view(), name='api-learner-chapter-course'),
    path('learner-chapter-course-subject/<int:user_id>/', LearnerChapterCourseSubjectView.as_view(), name='api-learner-chapter-course-subject'),
    path('learner-chapter-list/<int:subject_id>/<int:user_id>/', LearnerChapterListView.as_view(), name='api-learner-chapter-list'),
    path('learner-approve-chapter/<int:pk>/<int:studid>/', LearnerApproveChapterView.as_view(), name='api-learner-approve-chapter'),
    path('learner-approve-all-chapter/<int:userid>/<int:subject_id>/', LearnerApproveAllChapterView.as_view(), name='api-learner-approve-all-chapter'),
    path('learner-show-chapter/<int:subject_id>/<int:chapter_id>/', LearnerShowChapterView.as_view(), name='api-learner-show-chapter'),
    ###################################
    path('chapter-questions/', ChapterQuestionAPIView.as_view(), name='api-chapter-question'),
    path('chapter-results/', ChapterResultAPIView.as_view(), name='api-chapter-result'),
    path('chapter-result-details/', ChapterResultDetailsAPIView.as_view(), name='api-chapter-result-details'),
    path('activity/', ActivityAPIView.as_view(), name='api-activity'),
    path('activity-upload-csv/', ActivityUploadDetailsCSVAPIView.as_view(), name='api-activity-upload-csv'),
]

imran/LXP/learner/models.py
from django.db import models
from django.contrib.auth.models import User

imran/LXP/lxpapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, Sum
import requests
import humanize
import datetime


    
class UserProfile(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    regdate =  models.DateTimeField(default=datetime.datetime.now)
    contactno = models.CharField(default='',max_length=200)
    skills = models.CharField(default='',max_length=200)
    bio = models.CharField(default='',max_length=2000)
    profile_img = models.ImageField(upload_to='profile_img/', blank=True, null=True)

class UserPics(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    picpath = models.TextField(default='')
    pic = models.ImageField()

class LearnerDetails(models.Model):
        learner=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
        user_full_name = models.CharField(max_length=200)
        mobile = models.CharField(max_length=10)
        whatsappno = models.CharField(max_length=10,default='')
        profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    
class UserLog(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    login =  models.DateTimeField(default=datetime.datetime.now)
    logout = models.DateTimeField(default=datetime.datetime.now)
    dur = models.CharField(default='',max_length=200)
    session_id = models.CharField(default='',max_length=200)
class IsFirstLogIn(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.user

#Need to del
class Subject(models.Model):
    subject_name = models.CharField(max_length=200)

    def __str__(self):
        try:
            return self.subject_name
        except:
            return self
class Chapter(models.Model):
    chapter_name = models.CharField(max_length=200)
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.chapter_name
    
# class Course(models.Model):
#     subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
#     course_name = models.CharField(max_length=200)

#     def __str__(self):
#         return self.course_name

class MainHead(models.Model):
    mainhead_name = models.CharField(max_length=200)

    def __str__(self):
        try:
            return self.mainhead_name
        except:
            return self

class SubHead(models.Model):
    mainhead = models.ForeignKey(MainHead, on_delete=models.SET_NULL, null=True)
    subhead_name = models.CharField(max_length=200)

    def __str__(self):
        return self.subhead_name
    
class Course(models.Model):
    mainhead = models.ForeignKey(MainHead, on_delete=models.SET_NULL, null=True)
    subhead = models.ForeignKey(SubHead, on_delete=models.SET_NULL, null=True)
    course_name = models.CharField(max_length=200)
    description = models.CharField(max_length=1000,default='')
    whatlearn = models.CharField(max_length=1000,default='')
    includes = models.CharField(max_length=1000,default='')
    cat=(('1','Advanced'),('2','Easy'),('3','Intermideate'))
    themecolor=models.CharField(max_length=200,choices=cat,default='Green')
    tags = models.CharField(max_length=10000,default='')
    image = models.CharField(max_length=1000,default='')
    banner = models.CharField(max_length=1000,default='')
    price = models.IntegerField(default=0)
    
    def __str__(self):
        return self.course_name

class CourseChapter(models.Model):
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    subject = models.ForeignKey(Subject, on_delete=models.SET_NULL, null=True)
    chapter = models.ForeignKey(Chapter, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.chapter.chapter_name


class Topic(models.Model):
    topic_name = models.CharField(max_length=200)
    chapter = models.ForeignKey(Chapter, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.topic_name


    

###################################
def getHumanizedTimeString(seconds):
      return humanize.precisedelta(
         datetime.timedelta(seconds=seconds)).upper(). \
         replace(" month".upper(), "m.").replace(" months".upper(), "m.").replace(" days".upper(), "d.").replace(
         " day".upper(), "d.").replace(" hours".upper(), "hrs.").replace(" hour".upper(), "hr.").replace(
         " minutes".upper(), "mins.").replace(" minute".upper(), "min.").replace(
         "and".upper(), "").replace(" seconds".upper(), "secs.").replace(" second".upper(), "sec.").replace(",", "")

SECRETS = {"SECRET_KEY": 'django-insecure-ycs22y+20sq67y(6dm6ynqw=dlhg!)%vuqpd@$p6rf3!#1h$u=',
           "YOUTUBE_V3_API_KEY": 'AIzaSyCBOucAIJ5PdLeqzTfkTQ_6twsjNaMecS8',
           "GOOGLE_OAUTH_CLIENT_ID": "699466001074-biu4pjifnphoh1raipgi5mm5bf72h1ot.apps.googleusercontent.com",
           "GOOGLE_OAUTH_CLIENT_SECRET": "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",
           "GOOGLE_OAUTH_SCOPES": ['https://www.googleapis.com/auth/youtube']}
class Tag(models.Model):
    name = models.CharField(max_length=69)
    created_by = models.ForeignKey(User, related_name="playlist_tags", on_delete=models.SET_NULL, null=True)

    times_viewed = models.IntegerField(default=0)
    times_viewed_per_week = models.IntegerField(default=0)
    # type = models.CharField(max_length=10)  # either 'playlist' or 'video'

    last_views_reset = models.DateTimeField(default=datetime.datetime.now)

class Video(models.Model):
    # video details
    video_id = models.CharField(max_length=100)
    name = models.CharField(max_length=100, blank=True)
    duration = models.CharField(max_length=100, blank=True)
    duration_in_seconds = models.BigIntegerField(default=0)
    thumbnail_url = models.TextField(blank=True)
    published_at = models.DateTimeField(default=datetime.datetime.now)
    description = models.TextField(default="")
    has_cc = models.BooleanField(default=False, blank=True, null=True)
    liked = models.BooleanField(default=False)  # whether this video liked on YouTube by user or not

    # video stats
    public_stats_viewable = models.BooleanField(default=True)
    view_count = models.BigIntegerField(default=0)
    like_count = models.BigIntegerField(default=0)
    dislike_count = models.BigIntegerField(default=0)
    comment_count = models.BigIntegerField(default=0)

    yt_player_HTML = models.TextField(blank=True)

    # video is made by this channel
    # channel = models.ForeignKey(Channel, related_name="videos", on_delete=models.SET_NULL, null=True)
    channel_id = models.TextField(blank=True)
    channel_name = models.TextField(blank=True)

    # which playlist this video belongs to, and position of that video in the playlist (i.e ALL videos belong to some pl)
    # playlist = models.ForeignKey(Playlist, related_name="videos", on_delete=models.SET_NULL, null=True)

    # (moved to playlistItem)
    # is_duplicate = models.BooleanField(default=False)  # True if the same video exists more than once in the playlist
    # video_position = models.IntegerField(blank=True)

    # NOTE: For a video in db:
    # 1.) if both is_unavailable_on_yt and was_deleted_on_yt are true,
    # that means the video was originally fine, but then went unavailable when updatePlaylist happened
    # 2.) if only is_unavailable_on_yt is true and was_deleted_on_yt is false,
    # then that means the video was an unavaiable video when initPlaylist was happening
    # 3.) if both is_unavailable_on_yt and was_deleted_on_yt are false, the video is fine, ie up on Youtube
    is_unavailable_on_yt = models.BooleanField(
        default=False)  # True if the video was unavailable (private/deleted) when the API call was first made
    was_deleted_on_yt = models.BooleanField(default=False)  # True if video became unavailable on a subsequent API call

    is_planned_to_watch = models.BooleanField(default=False)  # mark video as plan to watch later
    is_marked_as_watched = models.BooleanField(default=False)  # mark video as watched
    is_favorite = models.BooleanField(default=False, blank=True)  # mark video as favorite
    num_of_accesses = models.IntegerField(default=0)  # tracks num of times this video was clicked on by user
    user_label = models.CharField(max_length=100, blank=True)  # custom user given name for this video
    user_notes = models.TextField(blank=True)  # user can take notes on the video and save them

    # for new videos added/modified/deleted in the playlist
    video_details_modified = models.BooleanField(
        default=False)  # is true for videos whose details changed after playlist update
    def __str__(self):
        return str(self.name)

class Playlist(models.Model):
    tags = models.ManyToManyField(Tag, related_name="playlists")
    # playlist is made by this channel
    channel_id = models.TextField(blank=True)
    channel_name = models.TextField(blank=True)

    # playlist details
    is_yt_mix = models.BooleanField(default=False)
    playlist_id = models.CharField(max_length=150)
    name = models.CharField(max_length=150, blank=True)  # YT PLAYLIST NAMES CAN ONLY HAVE MAX OF 150 CHARS
    thumbnail_url = models.TextField(blank=True)
    description = models.TextField(default="No description")
    video_count = models.IntegerField(default=0)
    published_at = models.DateTimeField(default=datetime.datetime.now)
    is_private_on_yt = models.BooleanField(default=False)
    videos = models.ManyToManyField(Video, related_name="playlists")

    # eg. "<iframe width=\"640\" height=\"360\" src=\"http://www.youtube.com/embed/videoseries?list=PLFuZstFnF1jFwMDffUhV81h0xeff0TXzm\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"
    playlist_yt_player_HTML = models.TextField(blank=True)

imran/LXP/learner/forms.py
from django import forms
from django.contrib.auth.models import User

imran/LXP/templates/staff/chapterquestion/staff_add_chapterquestion.html
{% extends 'staff/staffbase.html' %}
{% load widget_tweaks %}
{% block content %}
<link rel="stylesheet" href="/static/getskills/css/style.css">

<body>
  <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class=""><a href="../../../../staff/staff-dashboard">Dashboard</a></li>
        <li class=""><a href="../../../../staff/staff-view-chapterquestion">View Chapter
            Questions</a></li>
        <li class="" aria-current="page">Add Chapter Question</li>
      </ol>
    </nav>
  </div>

  <h2 style="text-align:center;">Add Chapter Question</h2>
  {% if messages %}
  {% for message in messages %}
  {{ message }}
  {% endfor %}
  {% endif %}
  <form method="POST" id="chapterquestionForm" data-courses-url="{% url 'ajax_load_chapters' %}" autocomplete="off">
    {%csrf_token%}
    <div class="form-group">
      <div class="row">
        <div class="col-md-6 col-xl-6">
          <label for="subject_name">Subject Name</label>
          {% render_field chapterquestionForm.subject class="form-control"%}
        </div>
        <div class="col-md-6 col-xl-6">
          <label for="chapter_name">Chapter Name</label>
          {% render_field chapterquestionForm.chapter class="form-control"%}
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 col-xl-12">
          <label for="question">question</label>
          {% render_field chapterquestionForm.question class="form-control" placeholder="question" %}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-xl-6">
          <label for="option1">Option 1</label>
          {% render_field chapterquestionForm.option1 class="form-control"%}
        </div>
        <div class="col-md-6 col-xl-6">

          <label for="option2">Option 2</label>
          {% render_field chapterquestionForm.option2 class="form-control"%}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-xl-6">
          <label for="option3">Option 3</label>
          {% render_field chapterquestionForm.option3 class="form-control"%}
        </div>
        <div class="col-md-6 col-xl-6">
          <label for="option3">Option 4</label>
          {% render_field chapterquestionForm.option4 class="form-control"%}
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-xl-6">
          <label for="answer">Answer</label>
          {% render_field chapterquestionForm.answer class="form-control"%}
        </div>
        <div class="col-md-6 col-xl-6">
          <label for="marks">Marks</label>
          {% render_field chapterquestionForm.marks class="form-control"%}
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-xl-6">
        <button type="submit" class="btn btn-primary">ADD</button>
      </div>
    </div>
  </form>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_subject").change(function () {
      var url = $("#chapterquestionForm").attr("data-courses-url");  // get the url of the `load_topics` view
      var subjectId = $(this).val();  // get the selected subject ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: '{% url 'ajax_load_chapters' %}',                    // set the url of the request (= localhost:8000/hr/ajax/load-topics/)
        data: {
          'subject': subjectId       // add the subject id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_topics` view function
          $("#id_chapter").html(data);  // replace the contents of the topic input with the data that came from the server
        }
      });

    });
  </script>
  {% endblock content %}

imran/LXP/templates/staff/chapterquestion/staff_view_chapterquestion.html
{% extends 'staff/staffbase.html' %}
{% load widget_tweaks %}
{% block content %}
<link rel="stylesheet" href="/static/getskills/css/style.css">
<div>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class=""><a href="../../../../staff/staff-dashboard">Dashboard</a></li>
      <li class=""><a href="../../../../staff/staff-add-chapterquestion">Add Chapter Question</a></li>
      <li class="" aria-current="page">View Chapter Question</li>
    </ol>
  </nav>
</div>
<div class="card-body">
  <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>Subject Name</th>
          <th>Chapter Name</th>
            <th>View Questions</th>
        </tr>
      </thead>
      <tbody>
        {% for t in chapterquestions %}
        <tr>
          <td> {{t.subject_name}}</td>
          <td> {{t.chapter_name}}</td>
          <td><a class="btn btn-success btn-xs" href="{% url 'staff-view-chapterquestion-chapter' t.id  %}"><span class="fa fa-eye"></span></a></td>
        </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

imran/LXP/templates/staff/chapterquestion/staff_view_chapterquestion_chapter.html
{% extends 'staff/staffbase.html' %}
{% load widget_tweaks %}
{% block content %}
<link rel="stylesheet" href="/static/getskills/css/style.css">
<div>
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class=""><a href="../../../../staff/staff-dashboard">Dashboard</a></li>
      <li class=""><a href="../../../../staff/staff-add-chapterquestion">Add Chapter Question</a></li>
      <li class=""><a href="../../../../staff/staff-view-chapterquestion">View Chapter Question</a></li>
      <li class="" aria-current="page">View Chapter Question of <u> {{chapter_name}}</u></li>
    </ol>
  </nav>
</div>
<div class="card-body">
  <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <thead>
        <tr>
            <th>Chapter Question</th>
            <th>Option 1</th>
            <th>Option 2</th>
            <th>Option 3</th>
            <th>Option 4</th>
            <th>Answer</th>
            <th>Marks</th>
            <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for t in chapterquestions %}
        <tr>
          <td> {{t.question}}</td>
          <td> {{t.option1}}</td>
          <td> {{t.option2}}</td>
          <td> {{t.option3}}</td>
          <td> {{t.option4}}</td>
          <td>
            {{t.answer}}
          </td>
          <td> {{t.marks}}</td>
          <td><a class="btn btn-danger btn-xs" href="{% url 'staff-delete-chapterquestion' t.id  %}"
            onclick="return confirm('Are you sure?')"><span class="far fa-trash-alt"></span></a></td>
        </tr>
        {% endfor %}
        
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}